// get /api/reviews/products/:productId response

[
  {
      "id": 15,
      "product_id": 1,
      "user": "Jennyfer_Flatley",
      "score": 5,
      "title": "minus voluptatem repellendus",
      "body": "Pariatur est molestiae qui amet quo voluptatibus ut omnis. Et repudiandae autem et qui omnis ullam. Excepturi minima dolor. Quis at ut. Est dolorem aut voluptatem dolores quis facere et eligendi. Et hic possimus.",
      "recommend": 0,
      "date": "2020-10-10T17:11:55.000Z",
      "response_id": null,
      "ease": 3,
      "value": 1,
      "quality": 5,
      "appearance": 1,
      "works": 0,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 16,
      "product_id": 1,
      "user": "Leanne_Trantow31",
      "score": 5,
      "title": "fugit explicabo quia",
      "body": "Quae omnis exercitationem. Omnis quis aspernatur autem mollitia occaecati eum quo. Aut nam nostrum aspernatur et repellat vitae quibusdam. At ut et. Architecto illum cumque doloribus magnam molestiae non. Ullam ut vel quibusdam quisquam veritatis.",
      "recommend": 1,
      "date": "2020-07-28T00:09:32.000Z",
      "response_id": null,
      "ease": 2,
      "value": 2,
      "quality": 4,
      "appearance": 0,
      "works": 2,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 13,
      "product_id": 1,
      "user": "Dario.Ryan85",
      "score": 3,
      "title": "repudiandae magnam quibusdam",
      "body": "Et commodi eius natus vero rerum accusantium odio tempore facere. Labore voluptas impedit recusandae aspernatur aut. Amet sint deserunt consequatur illo qui. Similique veniam non aspernatur rem.",
      "recommend": 0,
      "date": "2020-07-20T05:36:04.000Z",
      "response_id": null,
      "ease": 1,
      "value": 4,
      "quality": 2,
      "appearance": 2,
      "works": 5,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 8,
      "product_id": 1,
      "user": "Eleanore_Schiller35",
      "score": 2,
      "title": "voluptatum maxime et",
      "body": "Dolorem vero provident officia qui deleniti. Cupiditate ut qui dolorem ullam laudantium quo iste. Autem beatae voluptatem voluptate animi quia. Nihil nobis et. Amet ad vel error ratione non vel doloremque repellat. Quaerat dolor alias ab eum labore rerum.",
      "recommend": 1,
      "date": "2020-07-06T14:33:02.000Z",
      "response_id": null,
      "ease": 2,
      "value": 2,
      "quality": 3,
      "appearance": 4,
      "works": 0,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 11,
      "product_id": 1,
      "user": "Cicero_Kovacek47",
      "score": 3,
      "title": "sunt beatae rerum",
      "body": "Recusandae vel quas quis in distinctio mollitia. Odit eos culpa facilis voluptatibus. Voluptas eius dolorem dolor. Aut architecto omnis sunt. Iste animi rem ea quo neque consequatur sit et distinctio.",
      "recommend": 0,
      "date": "2020-06-29T00:44:33.000Z",
      "response_id": null,
      "ease": 3,
      "value": 3,
      "quality": 4,
      "appearance": 2,
      "works": 4,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 6,
      "product_id": 1,
      "user": "Peter.Reilly22",
      "score": 5,
      "title": "perspiciatis enim inventore",
      "body": "Dolor qui itaque. Est ut pariatur. Necessitatibus quasi ut reiciendis praesentium quis non. Autem debitis sint et.",
      "recommend": 1,
      "date": "2020-06-07T12:34:18.000Z",
      "response_id": null,
      "ease": 4,
      "value": 4,
      "quality": 4,
      "appearance": 0,
      "works": 1,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 2,
      "product_id": 1,
      "user": "Grace.Marks79",
      "score": 4,
      "title": "quam nostrum animi",
      "body": "Quod maiores mollitia deserunt nisi. Deleniti atque est et modi. Et est nostrum distinctio pariatur. Quia qui voluptatem optio officia nihil vero nostrum explicabo at. Sapiente sit dolorem nemo similique.",
      "recommend": 0,
      "date": "2020-05-19T17:57:44.000Z",
      "response_id": null,
      "ease": 5,
      "value": 2,
      "quality": 4,
      "appearance": 4,
      "works": 4,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 5,
      "product_id": 1,
      "user": "Yolanda_Stoltenberg26",
      "score": 1,
      "title": "omnis maxime ut",
      "body": "In explicabo laborum est ducimus sint ipsam voluptatem et molestias. Eos aliquid modi quis hic assumenda sequi. Repellat qui qui aut. Non quam delectus culpa. Cupiditate eos in. Sequi eius quod.",
      "recommend": 0,
      "date": "2020-05-02T23:41:18.000Z",
      "response_id": null,
      "ease": 5,
      "value": 1,
      "quality": 2,
      "appearance": 2,
      "works": 5,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 9,
      "product_id": 1,
      "user": "Thelma_Dare90",
      "score": 4,
      "title": "porro accusantium sunt",
      "body": "Cupiditate aut eos a sit libero voluptatem enim. Aut ea molestias. Laboriosam ut illo fugit nobis perspiciatis aut consequatur labore. Et nulla dolor nisi sunt quae laborum ad illo quaerat.",
      "recommend": 0,
      "date": "2020-05-02T05:58:16.000Z",
      "response_id": null,
      "ease": 4,
      "value": 5,
      "quality": 4,
      "appearance": 0,
      "works": 4,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 12,
      "product_id": 1,
      "user": "Ben.Herman",
      "score": 3,
      "title": "eos quos velit",
      "body": "Adipisci molestias qui nisi quod nulla consequatur harum dignissimos. Enim qui optio possimus pariatur odio illo eligendi velit hic. Id non tempora. Ad ut et dolor voluptate asperiores maiores deserunt nihil sit. Illo eum quis dolores quod.",
      "recommend": 1,
      "date": "2020-04-23T22:27:52.000Z",
      "response_id": null,
      "ease": 3,
      "value": 3,
      "quality": 0,
      "appearance": 2,
      "works": 5,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 3,
      "product_id": 1,
      "user": "June12",
      "score": 2,
      "title": "ut facilis ratione",
      "body": "Nesciunt molestias ullam rem. Eum qui voluptatum porro perspiciatis nobis. Dolorem autem dolor quia aspernatur aspernatur optio aspernatur qui.",
      "recommend": 1,
      "date": "2020-03-14T08:39:11.000Z",
      "response_id": null,
      "ease": 2,
      "value": 5,
      "quality": 5,
      "appearance": 3,
      "works": 0,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 7,
      "product_id": 1,
      "user": "Palma.Auer65",
      "score": 5,
      "title": "qui qui reiciendis",
      "body": "Sed tenetur est. Molestias rerum aut in et consequuntur qui illum et. Quae recusandae qui suscipit eligendi ut autem voluptatibus. Ipsa reiciendis eius necessitatibus. Earum praesentium molestiae.",
      "recommend": 1,
      "date": "2020-03-08T17:40:50.000Z",
      "response_id": null,
      "ease": 5,
      "value": 0,
      "quality": 4,
      "appearance": 3,
      "works": 1,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 1,
      "product_id": 1,
      "user": "Brett_Price",
      "score": 4,
      "title": "sint quos aut",
      "body": "Eligendi praesentium voluptates vel. Veniam in quidem et reiciendis. In officiis sunt qui commodi consequatur voluptatem soluta debitis qui. Culpa sit in explicabo sint voluptatem optio id quis vel. Aperiam ut ipsam id qui praesentium iusto. Ut in rerum c",
      "recommend": 0,
      "date": "2020-02-01T22:43:22.000Z",
      "response_id": 0,
      "ease": 1,
      "value": 5,
      "quality": 5,
      "appearance": 2,
      "works": 5,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 10,
      "product_id": 1,
      "user": "Jody_Zboncak",
      "score": 1,
      "title": "aperiam eligendi beatae",
      "body": "Tempora veniam repellat non atque recusandae ab assumenda deserunt qui. In veniam sed. Quibusdam atque inventore qui molestias quo sunt nobis aut. Cum quidem modi pariatur ex excepturi. Distinctio et fugiat. Reprehenderit optio laboriosam molestias minus.",
      "recommend": 1,
      "date": "2019-12-24T22:14:28.000Z",
      "response_id": null,
      "ease": 1,
      "value": 2,
      "quality": 5,
      "appearance": 5,
      "works": 3,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 14,
      "product_id": 1,
      "user": "Jennyfer43",
      "score": 5,
      "title": "inventore aliquid explicabo",
      "body": "Optio qui et ut blanditiis ab placeat animi delectus tempore. Reprehenderit debitis quas quo quis cum explicabo provident. Omnis molestias incidunt aut cumque fugiat animi. Ducimus atque laudantium voluptatem eveniet qui corporis dicta. Repellat quis cumq",
      "recommend": 0,
      "date": "2019-12-02T22:55:15.000Z",
      "response_id": null,
      "ease": 5,
      "value": 0,
      "quality": 5,
      "appearance": 5,
      "works": 2,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  },
  {
      "id": 4,
      "product_id": 1,
      "user": "Athena.Thiel",
      "score": 1,
      "title": "tenetur maxime fuga",
      "body": "Occaecati et sit deserunt quia ut deserunt minima eum. Deleniti voluptatibus aspernatur possimus quas ratione exercitationem ipsum. Porro quos aliquam est. Molestias error et omnis. Nam dignissimos consequatur incidunt qui veritatis. Officia rerum laborio",
      "recommend": 1,
      "date": "2019-11-02T08:12:43.000Z",
      "response_id": null,
      "ease": 1,
      "value": 3,
      "quality": 0,
      "appearance": 2,
      "works": 1,
      "createdAt": "2020-10-14T14:45:56.000Z",
      "updatedAt": "2020-10-14T14:45:56.000Z"
  }
]
